# Generated by Django 5.1.2 on 2024-12-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('CEL', 'Celular'), ('CAP', 'Capa'), ('ACC', 'Acessório')], max_length=3, null=True),
        ),
    ]
